// GENERATED by scripts/optimise-photos.mjs — do not edit by hand.
//
// Responsive WebP renditions of the brand photography. Each entry lists the
// widths that exist on disk so a component can build a correct srcset, and
// carries a tiny blurred placeholder so the layout never jumps while loading.

export type Photo = {
  slug: string;
  alt: string;
  /** width / height of the source, for reserving space before load */
  aspect: number;
  widths: number[];
  blurDataURL: string;
};

export const PHOTOS = [
  {
    "slug": "family-sunset",
    "alt": "A mother and father laughing with their young daughter on his shoulders at sunset",
    "aspect": 0.6667,
    "widths": [
      420,
      640,
      960,
      1440
    ],
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBgCdASoYACQAPxF8s1CsKKSisBqoAYAiCUAWwoIMuNxXtOx24jov2jlvhxUXQ3uZ4Pv8OJoDUik2aAD+6pXMPmytNp18yQXFHoMTBGwmrZkQKywdOW3hJQiDYe7XBmJmi24pVKgAHKRTcKmtCn2TFUt9J8fEsJYahTRWWhh2k6Rva482cK31bqBYScvd+I9WFKYdQB5wgZNklPm7AAAA"
  },
  {
    "slug": "family-picnic",
    "alt": "Parents sitting outdoors at golden hour with their three children leaning against them",
    "aspect": 0.6667,
    "widths": [
      420,
      640,
      960,
      1440
    ],
    "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACwBgCdASoYACQAPxF6sFOsJ6QiqrgMAYAiCUAYzBzJTj+BQ6Lto8HmSAzX7F8+ToPOT2QdSQStJ8oNpFBSoAD++Wh1Lhncf1IPIEFiHMQ3jRkHT4lYW8Eue03kIT/eT/tK8WbGZm/6660X1lAFw4Rcm1Br0w2hXnEUEpZYqxNLIzj8Yj4K1hAA"
  },
  {
    "slug": "carer-baby-beach",
    "alt": "A smiling carer holding a baby on her hip by the sea",
    "aspect": 0.6667,
    "widths": [
      420,
      640,
      960,
      1440
    ],
    "blurDataURL": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAACwBgCdASoYACQAPxGCuFWsKCUjJWmZgCIJZADKMvnzGMkIGnl/QZcrmTre811lV9eWyydMfLm6Y4UuhjSMgAD+9gYF2JYFOT3tNXmyCDTShEOsHuVXaj3Al5KWuLeYZvrxfxeP5iV1bn0/+nbhUWCDHTzBpc2UCHKADhcXZTGrNw7gcfYC2wcmgJ3gXkJIR3WzfHqcnAGCwBzrMYl+1h0PSFhCmywY3kAAAA=="
  },
  {
    "slug": "nanny-reading",
    "alt": "A nanny reading a picture book on a sofa with two young children",
    "aspect": 1.5,
    "widths": [
      420,
      640,
      960,
      1440
    ],
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAwCdASoYABAAPxF0slCsJqSisAgBgCIJZQC/OBrCbHe9M+47D8AA/pdP/X7dXfS55nkkBnXumTVI2sSk/fCja8NOkZiTPDuHC7Qm9yp47a0cSMwO2WucpAzFTOAA"
  },
  {
    "slug": "family-garden",
    "alt": "A family of five standing together in a garden, smiling at the camera",
    "aspect": 0.5627,
    "widths": [
      420,
      640,
      960,
      1440
    ],
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBgCdASoYACsAPwlup1ArpqMisA1RcCEJQBgyC6qh/4Ptm3/4Rk6wougIpyJShQSj4u2Cttb+LGaFcAD+79AfukpwnzeQ4B2NVdhES+Gx0Lb5XW7xDUCyISe/b3I+Jy57lRB55rDPQ8nC7jcjbPVNOLtvYABLwY26i5gfjAQVWPcGJslYecdptL4DEFTYY/RdcP1yDhjkCMXQk8QdAAAA"
  },
  {
    "slug": "family-balloons",
    "alt": "Parents holding their toddler daughter outdoors with a balloon",
    "aspect": 0.6667,
    "widths": [
      420,
      640,
      960,
      1440
    ],
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAADwBgCdASoYACQAPxF2r1AsJ6QisBqqqYAiCWgArAASTfDhW+rfB1tqn1TFPiDgHnDrctlJO9Ui5h3A7WFnbCgAAP7L1I2kQQuNx3CcMiMUOSXuv73R7FawPnfLNdbkzXlSCSU3UjTY/ldWLQA8vh0ou8pMN/4RJjh5xSxWfv6Ahxs2lxNwkKBB2kmRb+qJQ/2Etys95xSHnA/b4qzAlIAA"
  }
] as const satisfies readonly Photo[];

export type PhotoSlug = (typeof PHOTOS)[number]["slug"];

export function photo(slug: PhotoSlug): Photo {
  const found = PHOTOS.find((p) => p.slug === slug);
  if (!found) throw new Error(`Unknown photo: ${slug}`);
  return found;
}

/** Builds the srcset string for a photo from the widths that actually exist. */
export function srcSet(p: Photo): string {
  return p.widths.map((w) => `/photos/${p.slug}-${w}.webp ${w}w`).join(", ");
}

/** Largest rendition, used as the plain `src` fallback. */
export function largestSrc(p: Photo): string {
  return `/photos/${p.slug}-${p.widths.at(-1)}.webp`;
}
