import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the Supabase CLI at `supabase start` — bundled, minified
    // and not ours to lint.
    "supabase/.temp/**",
    // Generated from the photo pipeline.
    "src/lib/photos.ts",
  ]),
  {
    // Profile photos come from private storage as signed URLs that rotate every
    // hour, so next/image would re-fetch and re-cache them on every rotation for
    // no benefit. The bytes are already small: uploads are resized to 800px WebP
    // server-side in lib/onboarding/nanny-actions.ts before they are stored.
    // Brand photography does go through the responsive pipeline — see
    // components/ui/photo.tsx and scripts/optimise-photos.mjs.
    files: [
      "src/components/nanny/**",
      "src/app/nannies/**",
      "src/app/family/jobs/**",
      "src/app/nanny/**",
      "src/app/admin/**",
    ],
    rules: { "@next/next/no-img-element": "off" },
  },
  {
    rules: {
      // A leading underscore is the project's marker for "this parameter is
      // required by a contract we do not control" — the useActionState
      // signature, mostly. Removing them would break the signature.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
    },
  },
]);

export default eslintConfig;
