import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the Supabase CLI at `supabase start` — bundled, minified
    // and not ours to lint.
    "supabase/.temp/**",
    // Generated from the photo pipeline.
    "src/lib/photos.ts",
  ]),
  {
    rules: {
      // A leading underscore is the project's marker for "this parameter is
      // required by a contract we do not control" — the useActionState
      // signature, mostly. Removing them would break the signature.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
    },
  },
]);

export default eslintConfig;
