/**
 * Turns the source photography into responsive, mobile-friendly WebP.
 *
 * Mobile bandwidth is a product requirement, and the originals are 0.9–3.7 MB
 * JPEGs — exactly what must never reach a phone on a slow connection. Each
 * photo is emitted at four widths so the browser can pick the smallest one that
 * fits the layout, plus a tiny blurred placeholder to avoid a layout jump while
 * it loads.
 *
 * Run:  node scripts/optimise-photos.mjs
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const SOURCE_DIR = "/Users/cisca/Downloads";
const OUT_DIR = new URL("../public/photos/", import.meta.url).pathname;
const MANIFEST = new URL("../src/lib/photos.ts", import.meta.url).pathname;

/** Widths chosen for the breakpoints the product targets, smallest first. */
const WIDTHS = [420, 640, 960, 1440];

const PHOTOS = [
  {
    slug: "family-sunset",
    file: "pexels-danikprihodko-19510859.jpg",
    alt: "A mother and father laughing with their young daughter on his shoulders at sunset",
  },
  {
    slug: "family-picnic",
    file: "pexels-dmitry-rodionov-30660796.jpg",
    alt: "Parents sitting outdoors at golden hour with their three children leaning against them",
  },
  {
    slug: "carer-baby-beach",
    file: "pexels-rhea-jabagat-50266004-7937874.jpg",
    alt: "A smiling carer holding a baby on her hip by the sea",
  },
  {
    slug: "nanny-reading",
    file: "pexels-gustavo-fring-8770553.jpg",
    alt: "A nanny reading a picture book on a sofa with two young children",
  },
  {
    slug: "family-garden",
    file: "pexels-hussein-altameemi-782843-7944461.jpg",
    alt: "A family of five standing together in a garden, smiling at the camera",
  },
  {
    slug: "family-balloons",
    file: "pexels-shambhavi-kartik-2157979793-35077185.jpg",
    alt: "Parents holding their toddler daughter outdoors with a balloon",
  },
];

await mkdir(OUT_DIR, { recursive: true });

const manifest = [];

for (const photo of PHOTOS) {
  const source = path.join(SOURCE_DIR, photo.file);
  if (!existsSync(source)) {
    console.warn(`  ! missing source, skipping: ${photo.file}`);
    continue;
  }

  const input = await readFile(source);
  const meta = await sharp(input).metadata();
  const aspect = meta.width && meta.height ? meta.width / meta.height : 1;

  const sizes = [];
  for (const width of WIDTHS) {
    // Never upscale: a 420px-wide source stays 420px wide.
    if (meta.width && width > meta.width) continue;

    const out = await sharp(input)
      .rotate()
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: 76, effort: 5 })
      .toBuffer();

    const name = `${photo.slug}-${width}.webp`;
    await writeFile(path.join(OUT_DIR, name), out);
    sizes.push({ width, bytes: out.length, src: `/photos/${name}` });
  }

  // 24px blurred base64 placeholder — a few hundred bytes, inlined in the HTML.
  const tiny = await sharp(input)
    .rotate()
    .resize({ width: 24 })
    .blur(1.5)
    .webp({ quality: 30 })
    .toBuffer();

  manifest.push({
    slug: photo.slug,
    alt: photo.alt,
    aspect: Number(aspect.toFixed(4)),
    widths: sizes.map((s) => s.width),
    blurDataURL: `data:image/webp;base64,${tiny.toString("base64")}`,
  });

  const original = input.length;
  const largest = sizes.at(-1)?.bytes ?? 0;
  const smallest = sizes[0]?.bytes ?? 0;
  console.log(
    `${photo.slug}: ${(original / 1024).toFixed(0)} KB source → ` +
      `${(smallest / 1024).toFixed(0)} KB @${sizes[0]?.width}px, ` +
      `${(largest / 1024).toFixed(0)} KB @${sizes.at(-1)?.width}px`,
  );
}

const file = `// GENERATED by scripts/optimise-photos.mjs — do not edit by hand.
//
// Responsive WebP renditions of the brand photography. Each entry lists the
// widths that exist on disk so a component can build a correct srcset, and
// carries a tiny blurred placeholder so the layout never jumps while loading.

export type Photo = {
  slug: string;
  alt: string;
  /** width / height of the source, for reserving space before load */
  aspect: number;
  widths: number[];
  blurDataURL: string;
};

export const PHOTOS = ${JSON.stringify(manifest, null, 2)} as const satisfies readonly Photo[];

export type PhotoSlug = (typeof PHOTOS)[number]["slug"];

export function photo(slug: PhotoSlug): Photo {
  const found = PHOTOS.find((p) => p.slug === slug);
  if (!found) throw new Error(\`Unknown photo: \${slug}\`);
  return found;
}

/** Builds the srcset string for a photo from the widths that actually exist. */
export function srcSet(p: Photo): string {
  return p.widths.map((w) => \`/photos/\${p.slug}-\${w}.webp \${w}w\`).join(", ");
}

/** Largest rendition, used as the plain \`src\` fallback. */
export function largestSrc(p: Photo): string {
  return \`/photos/\${p.slug}-\${p.widths.at(-1)}.webp\`;
}
`;

await writeFile(MANIFEST, file);
console.log(`\nWrote ${manifest.length} photos to public/photos/ and src/lib/photos.ts`);
